# Generated by Django 4.1.3 on 2022-11-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_song_id_song_artiste_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
    ]
