# Generated by Django 4.1.3 on 2022-11-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_lyric_song_id_remove_song_artiste_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
