# Generated by Django 4.1.2 on 2022-10-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_id',
        ),
    ]
